# Generated by Django 4.2.7 on 2024-01-31 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField()),
                ('reservation_time_start', models.TimeField()),
                ('reservation_time_end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='insuranceinformation',
            name='patientinfo',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='patientinfo',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medicalhistory',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patientinfo',
        ),
        migrations.RenameModel(
            old_name='PatientInfo',
            new_name='UserInfo',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='InsuranceInformation',
        ),
        migrations.DeleteModel(
            name='MedicalHistory',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
        migrations.AddField(
            model_name='reservation',
            name='userinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.userinfo'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webapp.reservation'),
        ),
    ]
