# Generated by Django 4.2.6 on 2024-02-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_parkingspace_payment_reservation_vehicletype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('vehicle_type', models.CharField(max_length=255)),
            ],
        ),
    ]
