# Generated by Django 4.2.6 on 2024-02-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_reservationmodel_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmodel',
            name='vehicle_type',
            field=models.CharField(max_length=255),
        ),
    ]
